# Generated by Django 3.0.5 on 2021-03-26 03:29

import core.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('instituicao', djongo.models.fields.EmbeddedField(model_container=core.models.Instituicoes)),
            ],
        ),
    ]
