# Generated by Django 3.1.7 on 2021-03-29 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_profissional', models.CharField(choices=[('CRM', 'Medicina'), ('CRP', 'Psicologia'), ('XXX', 'Outros')], default='XXX', max_length=5)),
                ('uf', models.CharField(choices=[('SP', 'SaoPaulo'), ('0', 'OutrasLocalidades')], default='0', max_length=2)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='data_de_criacao')),
                ('nome', models.CharField(max_length=100)),
                ('register_id', models.CharField(max_length=10)),
                ('rank', models.IntegerField()),
                ('raw_validation', models.JSONField(blank=True, null=True, verbose_name='raw validation')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
        migrations.DeleteModel(
            name='Instituicoes',
        ),
    ]
